teams:
  - name: anoncreds-contributors
    maintainers:
      - ryjones
    members:
      - andrewwhitehead
      - berendsliedrecht
      - bryce-mcmath
      - dkulic
      - genaris
      - mikelodder7
      - swcurran
      - TelegramSam
      - TimoGlastra
      - WadeBarnes
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation

repositories:
  - name: .github
    teams:
      anoncreds-contributors: maintain
      lf-staff: maintain
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
